### PR TITLE
added item summary plots

### PR DESCRIPTION
**Pull request by tyarkoni**
Just a quick update to the notebook to add horizontal bar plots displaying response summaries for all the items with numerical responses. This is pretty ugly and I'm completely ignoring the categorical variables, but I think it's a different window into responses than the mean alone provides.

### CODE REVIEW

**Review by KirstieJane — APPROVED** [review]
Looks good to me!

I ran it in binder and everything works 😸

**Comment by KirstieJane** [comment]
Left a review, but I'll let @emdupre do the actual merge I think (just in case!)

Update: added an issue (#2) if anyone wants to come along and make the figures jazzier when they read the blog

**Comment by emdupre** [comment]
Thanks for the ping, @KirstieJane ! Somehow I didn't get notified of this (and thus need to go figure out which GitHub settings need updating...).

I had actually also converted to stacked bar graphs locally :woman_facepalming: Those are what I put in the blog post but hadn't yet pushed the updated notebook ! So, I think I'll close this PR since it seems like I'll end up creating a big merge conflict for very similar content. Sorry about that !!!! I really appreciate you opening it, though -- and making the point about accurate data representation !

Please open more PRs (or issues !) if there's anything else you think needs updating or adding.

**Comment by tyarkoni** [comment]
No worries. Feel free to just close the PR—I think I like the look of your plots better.

**Pull request closed without merging**
